### ISSUE TITLE
Gnome session freezes when enabling copyous

### ISSUE THREAD

**Issue by jle64** [boerdereinar/copyous#56]
### Description

Enabling copyous on my computer (on which it used to work fine until an hour ago) (and btw I like it a lot, very nice clipboard manager) now makes the whole Gnome session freeze, forcing a hard reboot. Logging into Gnome again leads to a frozen session again, unless removing the extension (from a tty) before launching Gnome.

Removing all Gnome extensions, testing them one by one, doesn't causes any issue except when enabling (or removing and reinstalling) copyous, which causes the session to freeze.

I haven't been able to see any relevant error in journalctl output, the last lines before the last freeze where simply the copyous installation steps:
```
Dec 16 13:46:29 JonathanPC gnome-shell[6442]: Archive:  /tmp/VR0VH3.shell-extension.zip
Dec 16 13:46:29 JonathanPC gnome-shell[6442]:    creating: /var/home/jonathan/.local/share/gnome-shell/extensions/copyous@boerdereinar.dev/locale/
Dec 16 13:46:29 JonathanPC gnome-shell[6442]:    creating: /var/home/jonathan/.local/share/gnome-shell/extensions/copyous@boerdereinar.dev/locale/de/
Dec 16 13:46:29 JonathanPC gnome-shell[6442]:    creating: /var/home/jonathan/.local/share/gnome-shell/extensions/copyous@boerdereinar.dev/locale/de/LC_MESSAGES/
Dec 16 13:46:29 JonathanPC gnome-shell[6442]:   inflating: /var/home/jonathan/.local/share/gnome-shell/extensions/copyous@boerdereinar.dev/locale/de/LC_MESSAGES/copyous@boerdereinar.dev.mo
Dec 16 13:46:29 JonathanPC gnome-shell[6442]:    creating: /var/home/jonathan/.local/share/gnome-shell/extensions/copyous@boerdereinar.dev/locale/fr/
```

### Expected Behavior

Computer should not freeze

### Reproduction Steps

Install or enable copyous from extension manager.

### Extension Version

can't run command since I had to remove the extension but I tried the last one

### Environment

# System Details Report
---

## Report details
- **Date generated:**                              2025-12-16 14:06:07

## Software Information:
- **OS Name:**                                     Fedora Linux 43.20251005.n.1 (Silverblue Prerelease)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               49
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.17.0-63.fc43.x86_64

### Enabled Extensions

I've disabled them all

### Configuration

```
[/]
auto-hide-search=true
clipboard-history='keep-all'
clipboard-orientation='horizontal'
clipboard-position-horizontal='fill'
disable-hljs-dialog=false
header-controls-visibility='visible-on-hover'
history-length=100
item-height=90
item-width=300
open-clipboard-dialog-shortcut=['<Super>v']
paste-on-copy=true
remember-search=true
show-header=false
sync-primary=true
update-date-on-copy=false

[file-item]
file-preview-visibility='file-info'

[link-item]
link-preview-orientation='horizontal'
```

### Logs

(Adapting to limit output to the last boot that crashed)
```
LANG=C journalctl --boot -1 -f /usr/bin/gnome-shell /usr/bin/gjs /usr/lib/systemd/systemd-coredump
Dec 16 13:45:19 JonathanPC org.gnome.Characters[5685]: JS LOG: Characters Application started
Dec 16 13:45:19 JonathanPC org.gnome.Weath[5800]: ImportError: Unable to load file async from: resource:///org/gnome/Weather/js/service/main.js (La ressource dans « /org/gnome/Weather/js/service/main.js » n’existe pas)  
Dec 16 13:45:19 JonathanPC org.gnome.Weather.BackgroundService[5800]: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
                                                                      @/app/share/org.gnome.Weather/org.gnome.Weather.BackgroundService:9:4
Dec 16 13:45:20 JonathanPC flatpak[5685]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:981: FINISHME: support more multi-planar formats with DRM modifiers
Dec 16 13:45:20 JonathanPC flatpak[5685]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:949: FINISHME: support YUV colorspace with DRM format modifiers
Dec 16 13:45:21 JonathanPC flatpak[5886]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:981: FINISHME: support more multi-planar formats with DRM modifiers
Dec 16 13:45:21 JonathanPC flatpak[5886]: MESA-INTEL: warning: ../src/intel/vulkan/anv_formats.c:949: FINISHME: support YUV colorspace with DRM format modifiers
Dec 16 13:45:26 JonathanPC gnome-shell[2552]: Received error from D-Bus search provider io.github.kolunmi.Bazaar.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'io.github.kolunmi.Bazaar': activation request failed: unknown unit
Dec 16 13:45:26 JonathanPC gnome-shell[2552]: Received error from D-Bus search provider io.github.kolunmi.Bazaar.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer 'io.github.kolunmi.Bazaar': activation request failed: unknown unit
Dec 16 13:45:36 JonathanPC org.gnome.Characters[5685]: JS LOG: Characters Application exiting
```

**Comment by D1360-64RC14** [comment]
For those who can't enable the extentions, because Copyous keeps crashing the gnome shell, run

```
gnome-extensions disable copyous@boerdereinar.dev
```

in the terminal to disable it, until it's fixed.

**Comment by D1360-64RC14** [comment]
Same here. My gnome shell crashes when I enable the extension.

### System Information

**OS**: openSUSE 20251212 (Tumbleweed)
**OS Type**: 64-bit
**Kernel**: x86_64 Linux 6.18.0-2-default
**DE**: GNOME 49.2.2
**WM**: Mutter 49.2
**Windowing System**: Wayland

### Enabled Extensions

Disabled all of them.

### Logs

Output of my superuser `journalctl` when the extension is enabled.

> Extension was enabled exactly at 12:44:00

```
Dec 16 12:43:42 d1360l sudo[22325]:    diego : TTY=pts/0 ; PWD=/home/diego ; USER=root ; COMMAND=/usr/bin/journalctl --since -4min
Dec 16 12:43:42 d1360l sudo[22325]: pam_unix(sudo:session): session opened for user root(uid=0) by diego(uid=1000)
Dec 16 12:43:43 d1360l sudo[22325]: pam_unix(sudo:session): session closed for user root
Dec 16 12:44:00 d1360l gnome-shell[15250]: [Copyous] Using Gda 6.0 database
Dec 16 12:44:00 d1360l kernel: gdaWrkrTh0[22478]: segfault at 0 ip 0000000000000000 sp 00007f13577f9c98 error 14 likely on CPU 5 (core 9, socket 0)
Dec 16 12:44:00 d1360l kernel: Code: Unable to access opcode bytes at 0xffffffffffffffd6.
Dec 16 12:44:00 d1360l systemd-coredump[22479]: Process 15250 (gnome-shell) of user 1000 terminated abnormally with signal 11/SEGV, processing...
Dec 16 12:44:00 d1360l systemd[1]: Started Process Core Dump (PID 22479/UID 0).
Dec 16 12:44:02 d1360l systemd-coredump[22480]: [🡕] Process 15250 (gnome-shell) of user 1000 dumped core.
                                                
                                                Stack trace of thread 22478:
                                                #0  0x0000000000000000 n/a (n/a + 0x0)
                                                ELF object binary architecture: AMD x86-64
Dec 16 12:44:02 d1360l systemd[1]: systemd-coredump@7-22479-0.service: Deactivated successfully.
Dec 16 12:44:02 d1360l systemd[1]: systemd-coredump@7-22479-0.service: Consumed 1.665s CPU time.
Dec 16 12:44:02 d1360l org.gnome.Shell.Extensions[21963]: Lost connection to Wayland compositor.
Dec 16 12:44:02 d1360l xdg-desktop-portal-gtk[16293]: Error reading events from display: Broken pipe
Dec 16 12:44:02 d1360l google-chrome.desktop[18332]: Gdk-Message: 12:44:02.091: Lost connection to Wayland compositor.
Dec 16 12:44:02 d1360l kgx[22103]: Lost connection to Wayland compositor.
Dec 16 12:44:02 d1360l gnome-extensions-app[21947]: Lost connection to Wayland compositor.
```

### Configuration
```
[/]
disable-hljs-dialog=false
history-length=500
```

**Comment by boerdereinar** [comment]
Would you be able to send the clipboard.db file that crashed the session?

**Comment by jle64** [comment]
after looking on my side, I too appear to have a "bad" entry in `clipboard.db` that causes the issue. I'm not sharing the file since it's full of API tokens, but the last entry what just two lines of text separated by a bunch of line breaks, and indeed I'm able to reproduce the issue just by copying a text with a bunch of line breaks in the middle.

For example, if in the terminal I do:
```fish
printf 'a\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\n\\nb'
```
Then copying the output from `a` to `b` included freezes my session and I can only log into gnome again by removing `clipboard.db`.

**Comment by boerdereinar** [comment]
Hi I just pushed a fix for this. Would you be able to verify that [this build](https://github.com/boerdereinar/copyous/actions/runs/20545113559) works?

**Comment by linuxiorr** [comment]
I'm not sure If it's the same issue, but for me GNOME shell still crashes with the new build when enabling copyous.

When I try to log in after installing it at first I get black screen and after a moment it puts me back to log in screen. When I try to log in again, all my extensions get disabled, and to get a fully working system again I have to uninstall copyous.

**Comment by boerdereinar** [comment]
Then it probably is not related to that issue. Is anything logged when gnome shell crashes?

**Comment by jle64** [comment]
> Hi I just pushed a fix for this. Would you be able to verify that [this build](https://github.com/boerdereinar/copyous/actions/runs/20545113559) works?

Yes, it's OK for me. Thanks !

**Comment by guzmalito** [comment]
### Still reproduces on GNOME 50 / Wayland — with a diagnostic clue the original report was missing

I hit the exact freeze described in this issue, on a different environment, so it's not distro/hardware-specific. More importantly, I found the last log line before the hang, which points at where the freeze happens.

**Environment**
- Distro: CachyOS (Arch-based)
- GNOME Shell: 50.2 (Wayland session, GDM)
- GPU: AMD Radeon RX 9070 (Navi 48, RDNA4), amdgpu driver
- Copyous: e.g.o version 9 (GNOME 48/49/50)

**Symptom**
Session freezes hard right after entering the password at GDM (compositor locks; the rest of the machine is unreachable, journald stops flushing → looks like a hard freeze). Recovering requires booting to a TTY and disabling/removing the extension. It does **not** freeze when the extension is enabled *hot* in an already-running session — only when it loads during session startup. (This is why bisecting live didn't reproduce it for me at first.)

**Diagnostic clue (was missing in the original report)**
With other extensions removed so the log was clean, the GNOME Shell process for the user session logs this as its **very last line** before the freeze:

```
gnome-shell[PID]: [Copyous] Using JSON database
```

After that, nothing — the shell stops responding, and dependent services (xdg-desktop-portal, etc.) start timing out. So the hang happens at/after the JSON database load + clipboard hook-up during the extension's startup, on the shell's main thread (it blocks the compositor). My clipboard DB was tiny and valid JSON (~13 KB, 2 entries), so it doesn't seem to be DB size/corruption — more likely a synchronous operation on the main loop during init.

**Recovery for anyone stuck here**
Boot to a TTY (e.g. add `3` to the kernel cmdline, or Ctrl+Alt+F3 from the frozen greeter) and run:

```
gnome-extensions disable copyous@boerdereinar.dev
# or, to fully remove:
gnome-extensions uninstall copyous@boerdereinar.dev
```

Happy to grab more logs (full `journalctl -b -1` around the freeze) if useful.

**Comment by abulka** [comment]
Same freeze here — **Fedora Silverblue / GNOME Shell 50.4 / Wayland / Intel i915**, Copyous **2.0.1 (version 9)**. After a reboot I log in at GDM, and the screen goes blank: the shell never presents the desktop. No crash, no coredump, no OOM, nothing in dmesg — the shell process just stops responding during startup. The only way I got back in was booting to a TTY (runlevel `3`) and disabling user extensions.

Key detail: it reproduced on **both** my new and previous Silverblue deployments (mutter 50.4 **and** mutter 50.3), which rules out the OS update. The common factor is user-space — i.e. the extension.

The user-session shell's log simply ends like this (`journalctl -b <boot> -g "gnome-shell\[2956\]"`), with nothing after:

```
[Copyous] Using JSON database
JS ERROR: ImportError: Unable to load file async from: file:///var/home/andy/.local/share/copyous@boerdereinar.dev/highlight.min.js (Error opening file /var/home/andy/.local/share/copyous@boerdereinar.dev/highlight.min.js: No such file or directory)
```

This matches the June report exactly: last line `[Copyous] Using JSON database`, then silence. One extra clue in my case: `highlight.min.js` is **missing** from the data dir `~/.local/share/copyous@boerdereinar.dev/`, and that `ImportError` is the only error logged before the shell goes quiet. I don't know if it's the trigger, but it seems worth checking.

FWIW the whole failure is silent — no `systemd-coredump`, no segfault, no GPU errors — which is probably why it's hard to debug: it's a hang on the shell's main thread during startup, not a crash.

Happy to grab more logs or test a build.

**Comment by abulka** [comment]
Interestingly, Copyous `2.0.1` runs fine on my aarch64 VM — Fedora Silverblue, GNOME Shell 50.4, Wayland, all same as the failing machine. Deleting highlight.min.js from the data dir and rebooting didn't reproduce the freeze either. So the freeze isn't explained by the extension version, OS/shell versions, or the missing `highlight.js` file.
